### ISSUE TITLE
Web UI started showing a VersionError

### ISSUE THREAD

**Issue by menzo2003** [sdr-enthusiasts/docker-readsb-protobuf#107]
The Web UI map started showing the following error via my browser:   
VersionError: The requested version (11) is less than the existing version (304).

The map is also not centered on my position anymore when it starts and it very unresponsive when dring it over to my position.

It appears to have stared in the last few weeks.

**Comment by mikenye** [comment]
I know this sounds like a cop-out answer, but have you tried clearing your browser cache & cookies, or using a different browser?

**Comment by menzo2003** [comment]
Yeah, I don't get the error message on the other browsers, but it does start centered in the wrong position and is very sluggish.

You can also see a difference in the distance circles between chrome and firefox, but both start the map centered around Italy instead the Netherlands. image with circle around Italy is chrome, the other is firefox.
![adsb chrome](https://user-images.githubusercontent.com/31390707/177569963-0b7d8c9c-a880-468f-93bd-6df39f51eeae.png)
![adsb firefox](https://user-images.githubusercontent.com/31390707/177569989-893f65a1-5731-44aa-8414-2dd5fbe2ad75.png)

**Comment by etamtlosz** [comment]
I'm struggling with the same issue.
Logged in Chrome shows me a similar popup message 
![image](https://user-images.githubusercontent.com/7436784/178346874-a8edefe1-5985-463c-a5ca-6dfc6136e0a1.png)
and puts me exactly at the same location as @menzo2003 - somewhere next to Alessandria (Italy).
Incognito or other browser works perfectly. Could be Chrome extension that's messing up things.

**Comment by mikenye** [comment]
@mictronics are you able to take a look at this?

**Comment by mryan1** [comment]
Some more info from chrome console in case it is helpful
<img width="1403" alt="Screen Shot" src="https://user-images.githubusercontent.com/1656120/179403647-96d1caca-f179-427b-86ad-ec9a6de6abc0.png">
.

**Comment by menzo2003** [comment]
It looks like the last update has fixed the error for me.
