### ISSUE TITLE
Feature request: Healthcheck for dropped samples

### ISSUE THREAD

**Issue by 76rhodan** [sdr-enthusiasts/docker-readsb-protobuf#50]
Hi Mike,

This morning I noticed that I have dropped samples again.
![grafik](https://user-images.githubusercontent.com/53168891/138071066-2133e270-b648-4d77-9751-305c8586dd38.png)
A simple restart of the container resolved the issue as before. I still need to dig deeper into that (might be a transient thing with the PSU or SDR) but I started to wonder on how many stations this occurs unnoticed.
As a feature request: Would it be possible (and useful) to somehow integrate this into the healthchecks? If any dropped samples over time x, mark the container as degraded and throw an error message in the logs (or maybe even force a container internal readsb restart)?

**Comment by mikenye** [comment]
As discussed on Discord (posting here in case others are interested)...

Branch issue_50 contains a simple addition to the healthcheck script that will check for dropped samples.

To test, comment out your `image:` or `build:` line for the readsb service within your docker-compose.yml file, and replace with `build: https://github.com/mikenye/docker-readsb-protobuf.git#issue_50`, then run `docker-compose build`
and then `docker-compose up -d`.

Let me know how you go.

If this works as expected, I'll kick off a PR.
