### ISSUE TITLE
Container won't stop after kill command (Ubuntu 21.04, Raspi 3B+)

### ISSUE THREAD

**Issue by CalvinSchwartz** [sdr-enthusiasts/docker-readsb-protobuf#51]
Hello,
I currently have the issue that the container can't be stopped or killed and even somehow prevents a system reboot.
OS is Ubuntu 21.04 on a raspberrypi 3 running the latest version of the software:
- docker (1.5-2)
- docker-ce 5:20.10.10~3-0~ubuntu-hirsute
- containerd.io 1.4.11-1
- containerd golang-1.16 (= 1.16.2-0ubuntu1)
- OS: Ubuntu 21.04 aarch64
- Host: Raspberry Pi 3 Model B Plus Rev 1.3
- Kernel: 5.11.0-1021-raspi

In general the container works fine for some hours and after sometimes days I get error messages from piaware as well as fr24feed that there's no data received from readsb. Stopping or restarting piaware and fr24feed works fine and the webserver of readsab works but shows that no data is reveiced. After sending the stop or kill command to the container the webserver stops working but the container itselft seems to be still running. To stop it I have to hard-reset (pull the power cable) the raspberrypi and after reboot the container is stopped.
Just rebooting doesn't work (I waited 5 Minutes and nothing happened).

The same setup had no issues using Raspbian as OS.

Additionally something with the time seems to be wrong. The kill signal was send somewhere around 19:50 local, 17:50 UTC.

Log of container:

> 2021-10-26T14:09:53.865198324Z [telegraf] 2021-10-26T14:09:53Z E! [agent] Error writing to outputs.influxdb: could not write any address
> 
> 2021-10-26T14:09:54.821284162Z [telegraf] 2021-10-26T14:09:54Z E! [outputs.influxdb] When writing to [http://192.168.178.47:8087]: failed doing req: Post "http://192.168.178.47:8087/write?db=readsb": dial tcp 192.168.178.47:8087: connect: connection refused
> 
> 2021-10-26T14:09:54.821960041Z [telegraf] 2021-10-26T14:09:54Z E! [agent] Error writing to outputs.influxdb: could not write any address
> 
> 2021-10-26T14:09:55.830385553Z [telegraf] 2021-10-26T14:09:55Z E! [outputs.influxdb] When writing to [http://192.168.178.47:8087]: failed doing req: Post "http://192.168.178.47:8087/write?db=readsb": dial tcp 192.168.178.47:8087: connect: connection refused
> 
> 2021-10-26T14:09:55.830539978Z [telegraf] 2021-10-26T14:09:55Z E! [agent] Error writing to outputs.influxdb: could not write any address
> 
> 2021-10-26T14:09:56.823246452Z [telegraf] 2021-10-26T14:09:56Z E! [outputs.influxdb] When writing to [http://192.168.178.47:8087]: failed doing req: Post "http://192.168.178.47:8087/write?db=readsb": dial tcp 192.168.178.47:8087: connect: connection refused
> 
> 2021-10-26T14:09:56.824944928Z [telegraf] 2021-10-26T14:09:56Z E! [agent] Error writing to outputs.influxdb: could not write any address
> 
> 2021-10-26T14:09:57.020377956Z [cont-finish.d] executing container finish scripts...
> 
> 2021-10-26T14:09:57.137539337Z [cont-finish.d] 05-rtlsdr-biastee: executing... 
> 
> 2021-10-26T14:09:57.856642539Z [telegraf] 2021-10-26T14:09:57Z E! [outputs.influxdb] When writing to [http://192.168.178.47:8087]: failed doing req: Post "http://192.168.178.47:8087/write?db=readsb": dial tcp 192.168.178.47:8087: connect: connection refused
> 
> 2021-10-26T14:09:57.856776392Z [telegraf] 2021-10-26T14:09:57Z E! [agent] Error writing to outputs.influxdb: could not write any address
> 
> 2021-10-26T14:09:58.258301008Z [cont-finish.d] 05-rtlsdr-biastee: exited 0.
> 
> 2021-10-26T14:09:58.279907393Z [cont-finish.d] done.
> 
> 2021-10-26T14:09:58.288039774Z [s6-finish] waiting for services.
> 
> 2021-10-26T14:09:58.749522230Z [s6-finish] sending all processes the TERM signal.
> 
> 2021-10-26T14:10:01.819658967Z [s6-finish] sending all processes the KILL signal and exiting.

**Comment by derreisende77** [comment]
I do experience the same problems with Ubuntu 21.04 on a RPi 4. 
I had to deactivate influx v2 as the scripts intermittendly freeze in an uninterruptable state and a reboot is necessary. Sometimes it runs several days, sometimes they die after some hours.
Running readsb alone is a lot more „stable“ but 20 minutes ago it again stopped receiving RTLSDR packets.
